### ISSUE TITLE
Glitchy main form on Linux/Mono

### ISSUE THREAD

**Issue by MarcRiera** [leezer3/OpenBVE#47]
OpenBVE's main form is rather glitchy when running the program with Mono (at least on Linux, Ubuntu 15.10 in my case).

The most noticeable glitch is related to the .png images displayed as a placeholder when a route or train doesn't have a custom image. If I'm not mistaken, these images were recompressed some time ago to fix a related bug. However, I tried replacing them with the files from the last "official" build by OdakyufanAts, and those seem to work. Here's how the glitch looks like:

![captura de pantalla de 2016-03-10 19-54-22](https://cloud.githubusercontent.com/assets/12414284/13680811/7e1e901e-e6fa-11e5-89f8-4cdcd8e74440.png)

Another important glitch happens when selecting some routes and switching tabs to see the map and gradient profile. I thought it was related to the first glitch, but apparently not, it's quite random. Some of the Chashinai Railway routes display the map, while others don't. The in-game route briefing window is unaffected and always works correctly.

![captura de pantalla de 2016-03-10 19-58-29](https://cloud.githubusercontent.com/assets/12414284/13680812/7e2864fe-e6fa-11e5-93ba-a91a99e15aca.png)

Finally, during the last 2-3 days, the main form keeps reappearing after exiting the simulation. It didn't happen before, so it's surely related to a recent change. Also, the main form doesn't close when starting the simulation, but that has always happened and I think it's an old bug from the original builds.

**Comment by leezer3** [comment]
Please try today's most recent build:
http://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2016-03-10.tar.gz

The quit issue is fixed (That was a result of some of the crash handling tweaks)
All four of those PNGs recompressed, and seem to display OK for me now. I think it didn't like the alpha too much.

I've also added a blind fix for the blank map issue-
I think you're probably selecting a route whilst on the map tab, and for some reason it's not repainting when the preprocessor finishes. To combat this, it now specifically switches back to the description tab.
This is the one that may or may not work......

**Comment by MarcRiera** [comment]
Just tested the new build. Everything works fine when quitting the program, but the image and map issues persist. I think the PNG problem is related to compression: I have tried to open and save one of the images with KolourPaint and the output file is bigger, but it displays correctly. Or maybe it's just easier to use the original files (if libgdiplus was the sole culprit preventing using them in the past).

The map keeps failing to refresh. The first time a route is selected after opening the program it works flawlessly, but if the text encoding is changed or a different route is selected, it disappears until the program is restarted.

**Comment by leezer3** [comment]
Frustrating, both PNGs work OK at this end on the VM....
Does the PNG you saved with KolourPaint contain an alpha channel?

What I don't want to end up with is a situation where the same file produces different results on different systems.
Almost tempted to try and use the OpenBVE API png reader rather than libgidplus, but I'd rather not.....

libgdiplus was crashing with 2 or 3 of the original files (IIRC the small route icons), so it made sense at the time to assume that it was something funny with the way they'd been compressed, and just batch re-compress the lot.
Re-introducing the originals is a possibility, but I don't want to re-trigger the original crash either, especially as it wasn't possible to handle it as it was the system library dumping out directly.

**Comment by MarcRiera** [comment]
It contains an alpha channel indeed. I have now converted the four files and haven't found any more glitches with them so far.

I'm attaching the 4 converted PNGs here so you can try whether they work under other systems. If they do, given that the rest of files (and custom ones) work without issues, maybe it's not worth the hassle to rewrite that part of the code and we can just use them.
![route_error](https://cloud.githubusercontent.com/assets/12414284/13687662/f0909ed6-e71c-11e5-8ea3-72e4c92c9f70.png)
![route_unknown](https://cloud.githubusercontent.com/assets/12414284/13687661/f09041f2-e71c-11e5-9500-5b82ce1319dd.png)
![train_error](https://cloud.githubusercontent.com/assets/12414284/13687663/f093c796-e71c-11e5-92ea-3e5bc2ca9496.png)
![train_unknown](https://cloud.githubusercontent.com/assets/12414284/13687664/f100102c-e71c-11e5-9924-51bb631e7e5d.png)

**Comment by mgavioli** [comment]
I could not test all of them, but the two `route_*.png` I could test, do work fine here under Mono / Linux Mint 17.3.

**Comment by mgavioli** [comment]
Re-reading my post, I realized that I did not express myself clearly enough.

The **new** `.png`s posted by @MarcRiera work correctly under Mono/Linux (at least the two I could test); the original ones (currently in master) don't and are displayed as garbage.

It is probably the case to merge the new ones into master.

**Comment by leezer3** [comment]
Merged the PR.

Something funny is going on though, so will leave this issue open for a while in case anyone else sees problems.
I wonder if libgdiplus is handing them off to the graphics driver to decode or something, which could at least explain the inconsistency?
