### ISSUE TITLE
A freeobj's rotate behavior is strange from 1.7.1.0?

### ISSUE THREAD

**Issue by ginga81** [leezer3/OpenBVE#645]
### Description

A freeobj's rotate behavior is strange.
Jump to Ichinoseki, and look as this screenshot's position.
All of route at bellow link, and happen at Ichinoseki.
Only one freeobj's rotate is strange.
1.6.0.0 or 1.7.0.0 is correctly.
But newer version is strange.
If I create an another freeobj, this problem is may be fix.
But if it is a bug, I think that it should be fix for the future.
So, I report.
![1 6-1 7](https://user-images.githubusercontent.com/22734699/120880717-ee986400-c606-11eb-8373-a72808e2a64e.png)
![1 7 1 8以降](https://user-images.githubusercontent.com/22734699/120880736-0a036f00-c607-11eb-876c-0ab4fe023f52.png)

### Reproduction
Route:
Please download bellow link.

## Route

http://midnightexpginga81.web.fc2.com/touhoku_shinkansen/route_data/Touhogu-Shinkansen-Routedata-fromSendai_v0.06.01_EN.zip

## Train

This trouble is only route. So train is any.

## Logs

This trouble is no output log.

### Related information 

My PC's SPEC:

OS: Ubuntu18.04LTS(64bit)
Memory:31.4 GiB
CPU:AMD® Ryzen 7 2700x eight-core processor × 16
Graphic board:Radeon RX 590 Series (POLARIS10, DRM 3.33.0, 5.3.0-51-generic, LLVM 9.0.0)

**Comment by ginga81** [comment]
### Additinonal information:
freeobj using route csv file is 
/include/D1東北新幹線一ノ関駅停車v0.04.csv
line 857,868,870,880,892 and 894.
/include/D2東北新幹線一ノ関駅通過v0.04.csv
line 852,863,865,875,887 and 889.

freeobj's define and freeobj csv file is routefile's about line 1355-65:
.FreeObj(1062)	OpenObjs/Structures/shinkansen_ichinoseki-stays/shinkansen-ichinoseki-stopsign-stay.csv				,;一ノ関ホーム停止位置ステー

**Comment by leezer3** [comment]
Cause seems to be:
https://github.com/leezer3/OpenBVE/commit/1aace8f619f24964fd7e397c16186e6ca15f9f62

This got added, as it solved a completely different glitch at the time. My comment in the source was that this didn't appear right, but that it made things work.......

Interestingly, if we remove this, the turnouts in the route linked in the comment to the previous commit aren't broken either, which suggests to me that there must have been an underlying math bug somewhere that's been fixed.
I think it's most likely to be this little bit of fun and games:
https://github.com/leezer3/OpenBVE/commit/d18019107e7851457412db8ec9383574b86193e1

@s520 any thoughts before I change this one?

**Comment by s520** [comment]
Hmm, I checked the commit history, etc., but I couldn't tell at what point the change occurred.
I don't object to reverting https://github.com/leezer3/OpenBVE/commit/1aace8f619f24964fd7e397c16186e6ca15f9f62.

**Comment by ginga81** [comment]
The newest daily build is fixed!
Thank you very much!
![Screenshot from 2021-06-06 03-06-06](https://user-images.githubusercontent.com/22734699/120901230-8718fd80-c674-11eb-94fa-58eb3bd196db.png)

**Comment by leezer3** [comment]
Something is definitely still not right here.
The revert seems to have caused other glitches.

End of this thread:
https://bveworldwide.forumotion.com/t2115-transparency-errors-on-some-x-objects#20722

Take the following extremely cut-down example:
```
0,.ground 1,.back 1,.sta Test;09.00;09.01
26,.stop 0,
100,.railstart 1;-9.02;0.0;0
125,.curve 600;0,.rail 1;-5.58;0.0;1
150,.rail 1;-3.22,.freeobj 1;1;0;0;179.35
175,.railend 1;-1.64
```

Colum1 in the final matrix is what differs.
Correct: 6.09753914925601E-05 , 0.999985555068869 , -0.00537456375997376, 0
Incorrect: -2.83846809988678E-10 , 0.999985555068868 , 0.00537490963723027

**Comment by leezer3** [comment]
https://github.com/leezer3/OpenBVE/pull/397/commits/d44933c95d3f15180a521701be496632cfbecfee
Been excavating all the way back to the start of the new renderer.
I have the very nasty suspicion that our transform to Matrix4D isn't right. Looking at the code, we're ignoring the X component of the transform completely, which immediately seems suspicious.

cc @s520

**Comment by leezer3** [comment]
Still digging.
The original transformation order I think was actually correct. GL expects matrix multiplications to be done in reverse order, confusing as this is.....

The code converting the Transformation to a Matrix4D is an implementation of LookAt, which makes sense.
I think adapted from here? https://github.com/opengl-tutorials/ogl/blob/master/common/quaternion_utils.cpp#L54

StackOverflow suggests that there are edge cases in the LookAt algorithm.
https://stackoverflow.com/a/51170230/722627

---

The following branch contains a *nasty* workaround:
https://github.com/leezer3/OpenBVE/tree/MatrixBug

Just adds 0.000011459155903 degrees, which is un-noticable. This may be our best solution for the minute, unless anybody with a math degree would care to comment.....

**Comment by s520** [comment]
I'm sorry for the late reply.
It seems correct to apply `AuxTransformation` to the coordinates and then `BaseTransformation`.
https://github.com/leezer3/OpenBVE/blob/f8aa5b6e81b0dd999778b95f65324dd13acb8494/source/OpenBveApi/Objects/ObjectTypes/StaticObject.cs#L428-L429

Next, I changed it to cast `Transformation` individually to `Matrix4D` and I got the correct drawing result.
https://github.com/s520/OpenBVE/commit/91a892e2032a40ad706579a669503adce591edc5
![Ichinoseki](https://user-images.githubusercontent.com/29241703/121909813-418dbc00-cd69-11eb-86e7-dc9cb8d92e25.PNG)
![Hachiman-yama](https://user-images.githubusercontent.com/29241703/121909834-45214300-cd69-11eb-91ad-ed63993e2d7b.PNG)

>The code converting the Transformation to a Matrix4D is an implementation of LookAt, which makes sense.
>I think adapted from here? https://github.com/opengl-tutorials/ogl/blob/master/common/quaternion_utils.cpp#L54

This code seems to have been applied from there.
There is a bookmark for [this page](http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-17-quaternions/) in my browser.

**Comment by leezer3** [comment]
That definitely seems to fix things.

We also use that transform code in the following three other places:
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBveApi/Objects/ObjectTypes/AnimatedObject.cs#L811
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBveApi/Objects/ObjectTypes/AnimatedWorldObject.StateSound.cs#L142
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBveApi/Objects/ObjectTypes/AnimatedObjectCollection.cs#L64

---

I don't much like it though, I think it's masking a wider issue with the rotation math.
I've narrowed it down somewhat further to this today:
```
double Pitch = 180 * 0.0174532925199433;
Vector3 yPos = Vector3.Down;
Vector3 yNeg = Vector3.Down;
yPos.Rotate(Vector3.Right, Pitch);
yNeg.Rotate(Vector3.Right, -Pitch);
if (yPos != yNeg)
	throw new Exception();
```

As a 180 degree rotation, yPos and yNeg should be identical, but the Z is actually inverted.

**Comment by leezer3** [comment]
I *think* our root cause is a gimbal lock problem with the way our transforms are constructed by passing in three angles and the rotation axis:
https://en.wikipedia.org/wiki/Gimbal_lock

It might be worth converting the transforms to a matrix constructed with quaternions if this avoids the problem in the first place.

I'm still not exactly clear why the rotation above doesn't work (sorry....), but OpenTK has the same glitch, which suggests I've missed something in the algebra that means this is correct.....

**Comment by s520** [comment]
> I've narrowed it down somewhat further to this today:
> 
> double Pitch = 180 * 0.0174532925199433;
> Vector3 yPos = Vector3.Down;
> Vector3 yNeg = Vector3.Down;
> yPos.Rotate(Vector3.Right, Pitch);
> yNeg.Rotate(Vector3.Right, -Pitch);
> if (yPos != yNeg)
> 	throw new Exception();
> As a 180 degree rotation, yPos and yNeg should be identical, but the Z is actually inverted.
> 

I think the direct cause of this is that `sin(π)` and `sin(-π)` are not equal to zero.
```
sin(π) = 1.2246063538223773E-16
sin(-π) = -1.2246063538223773E-16
```
These two values are close to zero, but they are different values.

The rotate function is based on Rodrigues' rotation formula, which appears to be correct.
https://github.com/leezer3/OpenBVE/blob/a4440de0beb43d08748d630253827afc97213fa4/source/OpenBveApi/Math/Vectors/Vector3.cs#L551-L563

In your example the Z coordinate is `sineOfAngle`.
Since `sineOfAngle` is inverted, the Z coordinate is inverted.

**Comment by s520** [comment]
I didn't understand the difference between OpenBVE and OpenGL coordinate systems correctly, so I did it like https://github.com/leezer3/OpenBVE/commit/d44933c95d3f15180a521701be496632cfbecfee.
https://github.com/s520/OpenBVE/commit/b2048814f5d85bad739ea1f7029667097e3ad7bf will correctly convert from `Transform` to `Matrix4D`.

**Comment by leezer3** [comment]
Don't worry, my head is hurting too :)

**Comment by s520** [comment]
In addition, I suggest renaming the `BaseTransformation` and `AuxTransformation` of the following functions:
https://github.com/leezer3/OpenBVE/blob/ac627726ed8e113034106d020f15997bfcb5c9f0/source/LibRender2/BaseRenderer.cs#L370
These are misleading.
I think of renaming `BaseTransformation` to `WorldTransformation` and `AuxTransformation` to `LocalTransformation`.

**Comment by leezer3** [comment]
Sounds reasonable.
I think they were just the original names from michelle

**Comment by s520** [comment]
Thanks!
I will make a pull request after making this change after tomorrow.

**Comment by leezer3** [comment]
I've merged the most recent branch from @s520 into the master branch for the minute.
It might not be perfect yet, but I can't immediately find anything wrong.

Ideally, I'd quite like to push a release soon; The current master now has a lot of small issues fixed I'd like to get out into the general public build.

**Comment by ginga81** [comment]
My problems, https://github.com/leezer3/OpenBVE/issues/645 and route viewer cannot show animated object's issue(I searched, but I cannot find this issue, please close) has been fixed at the newest daily build.
So, I think that it is no problem.

**Comment by s520** [comment]
I apologize for the time it takes to respond because I'm not in good physical condition.
I've read the messages that are notified to me, but I need time to reply.

I renamed parameters and added comments about the transformation class. (https://github.com/leezer3/OpenBVE/pull/660)

**Comment by leezer3** [comment]
Absolutely no problem, please don't apologise.
Do whatever you can, that's more than enough.
