### ISSUE TITLE
[Question And Bug?]Collect some train problems

### ISSUE THREAD

**Issue by JunmoreHeavyBox** [leezer3/OpenBVE#821]
### Description

Please describe the issue you are experiencing.

1. ~~When the train jumps to any station, the original Noise of the train is not turned off. The Noise played the second time after the reset is superimposed on the sound of the game started before the reset.
Pay attention to the noise volume.
To eliminate the original noise, the train has to be derailed, but only to eliminate the noise of the last time. This issue can be a headache for trains that often use change (jump) stations, and the noise gets louder as the trains are reset more often in the game.~~

https://user-images.githubusercontent.com/114210303/195951793-7469b35c-6c27-4b9f-9da2-2b3de89fe025.mp4

2. ~~The classic problem. In Control Trailer mode (where the driver is not in the power car), it seems that the AI driver is unaware of the wheel skid of the locomotive located at the tail of the train and will only increase the gear of the traction handle to the end. It's not until the AI driver is in the power car that it's aware of the need to consider wheel slippage. I had to use the ReAdhesionDevice to limit traction. Although the ride is uncomfortable, it is a way for the driver to casually top up the traction and still get the train moving.
This question is not necessary for Multiple-Unit trains and "trains with good adhesion coefficients and loads".
But what good is it going to do? Customize RunInterval trains for the #329 ?
I've wanted to bring this up for a long time.~~

3. ~~Some errors have been found in the use of NotchDescriptions.
Master control handle brake position with HoldBrake: There are two unused notches texts between NotchHB and Notch1.
Locomotive brake handle: The text that should be Notch0 uses the text of Notch1.~~
```
<NotchDescriptions>
<Brake /> (EBn-1;HB; ; ;B1;B2;..;Bn-2) Master control handle brake position with HoldBrake
<Brake /> (EBn-1;HB;B1;B2;..;Bn-2) Natural
<LocoBrake /> (B1;B1;B2;..;Bn-1) Locomotive brake handle
<LocoBrake /> (R;B1;B2;..;Bn-1) Natural
</NotchDescriptions>
```

4. The classic problem. It's possible to push the AI train with your own car when bored.
During the process of pushing, the bogie will drift slowly towards the load.

https://user-images.githubusercontent.com/114210303/196785691-0d769ab0-4409-4aa7-8ca9-1adac921d98d.mp4

5. I tried to test the windshield function during 2D cab practice, and something went wrong.
Regardless of the "Rain" and "Snow" commands on the route, I always saw raindrops and snowflakes all over the panel, and I couldn't get them off with my wipers.
![无标题](https://user-images.githubusercontent.com/114210303/195951982-73463a5b-a54b-4d76-8446-f8ea00814109.png)

6. The Panel is abnormal.
I set the 3D cockpit interior space limit, but it actually looks a bit weird... Is it that I can't use it or something else?
Incorrect rendering seen in 2D and 3D cab switching, switching to the outside view and then cutting back to the inside view will return to normal.
I didn't have an inside model of my train yet, so I didn't bother reproduce the problem.

7. When the brake is not completely released and the adhesion of the track is too poor. When the train starts, in this case, the speedometer variable of the Animated object of the power car will not rotate for a short time, but in fact, acceleration or dynamic braking is still applied. It looks like a linear metro train constrained by simulated adhesion.
Focus on wheels, acceleration and speed.

https://user-images.githubusercontent.com/114210303/195946960-9d6216c6-7b4d-43e0-a043-bd5d19ff2aad.mp4

The question is not obvious and not much is necessary. This is a suggestion.

8. ~~xml train conversion problems
After converting the train to an XML train, there are two LoadingSways in the Car.xml file.~~
The Coupler section works properly in the Train.xml file. However, it does not work in the Car.xml file, which is equivalent to the Coupler section not being set in the ExtensionCFG.
The brake handle has an extra notch, which is an unthinking explicit conversion. Simply put, in TrainDAT I have 21 brake Notches, the maximum notch is 20 and the emergency brake is 21. whereas in TrainXML the maximum notch is 21 and the emergency brake is an extra 22. please add a subtraction to the conversion for the brake Notches. (I made a stupid mistake. The train I didn't take into account was using the HoldBrake device.)

9. ~~I accidentally tried the shortcut key, something made the game crash.
I accidentally used headlights and the game crashed. However, I didn't make headlights.
I apply the Windscreen part through the XML sound reference file. When I try to use the wiper, the game will crash.~~

### Reproduction

If the issue occurs in multiple routes/ trains, please provide one or two samples.
In order to reproduce the issue and debug it, it's helpful to have the following:

## Route

Please provide a link to where the route may be downloaded.

## Train

Please provide a link to the train may be downloaded.

## Logs

Logs may be accessed through the 'Report Problem' button on the bottom left of the screen.
Please provide a log, and a crash-log if the game actually crashes.

About the game crash, I tried to use the headlights.
[CrashHeadLightKey_log.txt](https://github.com/leezer3/OpenBVE/files/9789648/ErrorHeadLight_log.txt)
[CrashHeadLightKey_OpenBVE Crash- 2022.10.13[01.13].log](https://github.com/leezer3/OpenBVE/files/9789649/ErrorHeadLight_OpenBVE.Crash-.2022.10.13.01.13.log)

About the game crash, I tried the wiper in the case of using XML sound reference files.
[CrashWindSXMLSound_log.txt](https://github.com/leezer3/OpenBVE/files/9789652/ErrorWindSXMLSound_log.txt)
[CrashWindSXMLSound_OpenBVE Crash- 2022.10.12[21.19].log](https://github.com/leezer3/OpenBVE/files/9789653/ErrorWindSXMLSound_OpenBVE.Crash-.2022.10.12.21.19.log)

### Related information 

* Windows 7
* Method of control: keyboard and mouse
* OpenBVE Version: 1.8.4.2
* Render: Old (GL 1.2)- GL 3.0 not available

**Comment by leezer3** [comment]
Fixed some of the easier ones of these :)
Will try and get the rest sorted over the next few days.

**4** may prove to be somewhat of a challenge.
Pushing the AI train is (sorta) allowed by the physics systems. If derailments are disabled, I think it'll push in pretty much any situation, and it's at least theoretically valid to do so.
Might want a on-screen message if you collide or something, but I'm not sure about going much further.

**Comment by JunmoreHeavyBox** [comment]
> 4. The classic problem. It's possible to push the AI train with your own car when bored.
>     During the process of pushing, the bogie will drift slowly towards the load.

A video presentation of the problem

https://user-images.githubusercontent.com/114210303/196785691-0d769ab0-4409-4aa7-8ca9-1adac921d98d.mp4

The video is a little noisy...

**Comment by leezer3** [comment]
I think the noise issue should now be fixed, we weren't checking whether a CarSound was already playing before re-starting it.
Not usually an issue, as most CarSounds are single play (bings etc.), or are stopped / started on a per-frame basis (plugin sounds)

This might have unwanted effects however, so please keep a slight eye on that.

**Comment by leezer3** [comment]
I think the notch description code should now be right as well. 
(a new build will generate in a few minutes)

Will try and look into what's happening with the windscreen later or tomorrow.

**Comment by JunmoreHeavyBox** [comment]
Issues 1,2,8 have been verified as fixed! (＾◡＾)
More issues that have been fixed will be tested at a later date.

### Some questions
9. In the daily snapshot I tried to use my train to test other issues and the game crashed.
 - Logs
[OpenBVE Crash- 2022.10.20[19.37].log](https://github.com/leezer3/OpenBVE/files/9829788/OpenBVE.Crash-.2022.10.20.19.37.log)
[log.txt](https://github.com/leezer3/OpenBVE/files/9829790/log.txt)

10. In TrainXML, a powered car that should make a motor sound has no motor sound if the car is not in the MotorCar index calculated by TrainDAT.
This forced me to use pure MotorCar in TrainDAT to solve this problem, after all the XML MotorCar assignment takes precedence. But this also led to another problem. In order to get the air brakes to work properly, I had to set the BrakeControlType in TrainDAT to 0 or set BrakeControlSpeed to infinite.

**Comment by leezer3** [comment]
Fudge, the MotorSound crash is my fault. Fixed that.

With regards to the XML motor sounds issue, this looks to me to occur if the **train.xml** is used without a **sound.xml**
Try the latest build and see if that helps.
Alternatively, adding a per-car sound.xml file should work around the issue.

Not quite sure exactly what you're doing with the air brakes to mess up the BrakeControl speed at the minute, still thinking about that one.....

**Comment by JunmoreHeavyBox** [comment]
In TrainDAT all vehicles are power cars and the assignment of power cars to XML trains is a prerequisite.
Vehicle indexes 0 (or n-3),1 (or n-2) and 2 (or n-1) for trains hauled by multi-unit locomotives are locomotives, whereas in TrainDAT it is assumed that it is the rolling stock then the vehicle index of the power car is calculated and assigned. This is the point of this problem.
The motor sound and brake control characteristics follow the arrangement of the power car indexes calculated and assigned in TrainDAT, even in XML trains. It is just that XML Train defines whether any vehicle is a powered vehicle or not and the acceleration.
What can I do in order to use XML Train? I set the number of powered vehicles in TrainDAT to the number of train vehicles, ignoring trailers, and then the brake control characteristics are assigned to all vehicles. I either make the electric and air brakes work together, or use only the air brakes.
Otherwise those trailers that don't have electric braking are treated as if they had electric braking for the power cars and then air braking is regulated.

I did mention something about the **Sound[CarIndex].xml** you mentioned. See https://github.com/leezer3/OpenBVE/issues/820/#issuecomment-1272625981 for details

**Comment by JunmoreHeavyBox** [comment]
(-_-)

Before the fix for issue 3, the handle descriptions were stretched to accommodate the XML notch descriptions and didn't seem to take into account too many characters. However, the handle descriptions tested now appear to overlap a little.
The disappearance of the notch description for locomotive brakes is no longer limited to the interface size setting.
![NDBug](https://user-images.githubusercontent.com/114210303/198856696-dbeda2b2-d5c8-4fdb-98aa-0fe62cacbb50.png)

The train handle type is combined type. The game crashes if the brake notch is not in the emergency brake.

## Logs
[OpenBVE Crash.log](https://github.com/leezer3/OpenBVE/files/9894793/OpenBVE.Crash.log)
[log.txt](https://github.com/leezer3/OpenBVE/files/9894792/log.txt)

**Comment by JunmoreHeavyBox** [comment]
@leezer3 I am sorry to disturb you, I have waited for a long time without seeing your response.

**Comment by JunmoreHeavyBox** [comment]
It looks like the motors on some XML trains don't make a sound, and the power cars on these trains are a bit far from the driver's car. The problem is not fixed very well...
To start reading here, I don't want to repeat.
> Motor sound and braking control characteristics follow the indexed arrangement of the power vehicles assigned by calculation in TrainDAT...

If nothing is changed, I would like the XML motor sound to revert to the way it was before the restoration for the time being.

**Comment by leezer3** [comment]
All I've done is to strikethrough the stuff that's been changed.
Otherwise it gets *really* confusing trying to read back through things......

It appears to work for me at the minute, which makes me suspect something in the configuration is interacting with something else.
Can you please share an example train for which the motor car sounds aren't working as you want?

Don't really need the actual sound files (can just dump in generics), exterior or anything, just the train.dat, sound.cfg, extensions.cfg and any XMLs.

**Comment by leezer3** [comment]
OK, try the build from today.

I think I might have got to the bottom of this- If the first motor car was not one set via train.dat, this was confusing matters.

**Comment by Kenny-Hui** [comment]
Latest nightly build 2022-11-14:
```
00:15:58  Unsupported motor sound type in XML node Motor
00:15:58  Unsupported motor sound type in XML node Motor
00:15:58  Unsupported motor sound type in XML node Motor
00:15:58  Unsupported motor sound type in XML node Motor
00:15:58  Unsupported motor sound type in XML node Motor
00:15:58  Unsupported motor sound type in XML node Motor
```
See if this helps [repo.zip](https://github.com/leezer3/OpenBVE/files/10014429/repo.zip)

**Comment by JunmoreHeavyBox** [comment]
I don't understand what tests you had done?

**Comment by leezer3** [comment]
Me?

A large amount of messing around with a rather large train collection.

The basic trouble however is that users do 'unexpected' things, or try to design something different to the initial test case I'd worked up ;)
There are large amounts of interacting subsystems, many of which use assumptions calculated on the internal rules of the original train.dat

**Comment by JunmoreHeavyBox** [comment]
I am asking @Kenny-Hui

**Comment by JunmoreHeavyBox** [comment]
Having sorted out the motor sound issue, there are still a few things to sort out.
In Issue 8 and "The disappearance of the notch description for locomotive brakes"
I'm not sure if there's anything else still tied to TrainDAT's pre-calculated power car index...

**Comment by Kenny-Hui** [comment]
> I am asking @Kenny-Hui 
> I don't know what he meant.
> A sample file and
> > `00:15:58  Unsupported motor sound type in XML node Motor`

I can't get the motor sound to play on an xml train on the latest Nightly Build either and has always worked before, is this another bug?

(I should've also included the actual sound instead of just the xml, but oh well)

**Comment by JunmoreHeavyBox** [comment]
My problem here is the same, in the case of using XML sound files.

**Comment by JunmoreHeavyBox** [comment]
I tested it and it should be the latest daily build only that has the XMLSound file motor sound fault.

**Comment by leezer3** [comment]
Nope, it's me, try again with the most recent build :(

(Missed the case where XML was being used as a replacement for sound.cfg with a non-default motor car)

**Comment by Kenny-Hui** [comment]
> Nope, it's me, try again with the most recent build :(
> 
> (Missed the case where XML was being used as a replacement for sound.cfg with a non-default motor car)
> 
> FWIW, the sounds themselves aren't really helpful as such and just add extra to what you're uploading. I can replace with generic stuff easily enough, and for testing any specific sound issues, I tend to replace them with a chime or something anyway as that's normally much easier to distinguish.

Thanks, that solves it.

**Comment by JunmoreHeavyBox** [comment]
A crash related to TFO.
It is normal in the official version.

 - Logs
[log.txt](https://github.com/leezer3/OpenBVE/files/10037779/log.txt)
[OpenBVE Crash- 2022.11.18[12.35].log](https://github.com/leezer3/OpenBVE/files/10037780/OpenBVE.Crash-.2022.11.18.12.35.log)

**Comment by leezer3** [comment]
Fixed, another case of the same issue above....

**Comment by JunmoreHeavyBox** [comment]
Thanks for the fix!

**Comment by JunmoreHeavyBox** [comment]
Problem with the spacing between the two of cars in TFO
When setting Reversed to True in the TFO file, the spacing between train cars is incorrect.
It looks like the coupler index 0 becomes 1, 1 becomes 2 and so on. The original car coupler index 0 is the default value.

**Comment by leezer3** [comment]
Thanks, fixed.

**Comment by leezer3** [comment]
No 7:
https://github.com/leezer3/OpenBVE/blob/master/source/TrainManager/Car/CarBase.cs#L1376

The speedometer variable comes from the _Percieved Speed_ which takes into account wheelspin / wheelock, although these are approximated as the original code doesn't really have a rotating wheel concept, just a series of fudges based upon magic numbers.

If you're looking for the absolute speed value, try **Speed** or **Speed[CarIndex]** animation variables.

There's nothing which currently takes into account wheelspin directly in terms of wheel rotations. 
As an approximate fudge with recently added variables, try multiplying the current speed by 100 or so if the **Wheelslip** variable is 1.

**Comment by JunmoreHeavyBox** [comment]
I'm so stupid, I didn't think about the If function to determine acceleration thinking very thoroughly. I think question 7 is basically almost.

**Comment by JunmoreHeavyBox** [comment]
```
Value+Delta*If[If[Speed<0,AccelerationMotor<0,AccelerationMotor>0],If[WheelSlip,Speedometer,Speed],Speedometer]/RADIUS
;Replaces the Speedometer variable in wheel spin function.
```
This is one If function I can think of to detect positive acceleration to solve the rotation problem when the wheel is locked.

However, it is an unsolved mystery that the motor still has braking force when the wheels are locked. (Except for linear motors)

**Comment by JunmoreHeavyBox** [comment]
To solve the unsolved mystery of electric braking, add "and the wheels are not locked" to the motor deceleration action conditions. If it solves the problem.

**Comment by JunmoreHeavyBox** [comment]
Then there are the ones that were missed.
No.11 and
> The disappearance of the notch description for locomotive brakes is no longer limited to the interface size setting. ![NDBug](https://user-images.githubusercontent.com/114210303/198856696-dbeda2b2-d5c8-4fdb-98aa-0fe62cacbb50.png)

**Comment by JunmoreHeavyBox** [comment]
@leezer3 I want you to address the issue of forgetting to fix it.
Read the last reviews.

**Comment by leezer3** [comment]
Should now be fixed I think- It was there, just stuck behind the others.

**Comment by JunmoreHeavyBox** [comment]
The description of the loco brake handle is still missing.

**Comment by JunmoreHeavyBox** [comment]
@leezer3 The description of the loco brake handle is still missing. With label rendering and no text.

**Comment by JunmoreHeavyBox** [comment]
Bring up the issue of the handle description of the locobrake handle again.
I can't see the text and it's still a grey block when I use the locobrake.
![image](https://user-images.githubusercontent.com/114210303/229653255-98fa89e2-6499-4d40-9869-c03137fd18cc.png)

**Comment by JunmoreHeavyBox** [comment]
@leezer3 Excuse me.
> Bring up the issue of the handle description of the locobrake handle again.
> I can't see the text and it's still a grey block when I use the locobrake. 
> Although the LocoBrake block was working fine until it was NotchDescriptions fixed.
![image](https://user-images.githubusercontent.com/114210303/229653255-98fa89e2-6499-4d40-9869-c03137fd18cc.png)

Please fix it, after which I would like to close the issue.

**Comment by JunmoreHeavyBox** [comment]
That's it.

Close the issue.
