### ISSUE TITLE
[Bug] Switching route in quick succession would crash in the main menu

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#917]
### Description

Sometimes, switching between 2 routes very quickly in the main menu. (Easier done in the "Recently Used" tab) would cause an error.
![image](https://github.com/leezer3/OpenBVE/assets/28094366/78e0e98b-3971-4024-bcb7-a0c9624e12c9)

### Reproduction

1. Launch OpenBVE
2. In the route tab, go to the "Recently Used" tab.
3. Click 2 route in very quick succession
4. Witness crash

## Logs
[openBVE Bug Report30_07_2023.zip](https://github.com/leezer3/OpenBVE/files/12209285/openBVE.Bug.Report30_07_2023.zip)

### Related information 

* Operating system: Debian 12 (Bullseye)
* Method of control: Keyboard
* OpenBVE Version: Latest Nightly Build

**Comment by leezer3** [comment]
Hmm...

I can't reproduce this at the minute. I'd suspect it's going to be timing related, and the fact that this is a pretty well specced machine doesn't help in that regard.
The crash is being caused when it attempts to load the plugins, so I'm wondering if this is a thread timing issue. The commit *may* help.

**Comment by Kenny-Hui** [comment]
Still the same crash on the latest Nightly build (I believe it is v1.7.1370.1061)

**Comment by Kenny-Hui** [comment]
Interesting, the problem still exist under mono, but doesn't occur on Windows, so I think this is a mono specific issue?

**Comment by leezer3** [comment]
*Probably* but without reproducing it I don't know specifically.
Unfortunately, the Mono forms implementation is (as I think you know) now essentially abandoned.

Not sure this is worth digging into too much further, especially as I can't reproduce :(

**Comment by Kenny-Hui** [comment]
Probably not, or at least it seems to only happen on specific configuration and probably won't affect the masses.

I'll leave this issue opened just in case though.

**Comment by ginga81** [comment]
Didn't reproduce on my Ubuntu 20.04 + this version of mono.
How about trying Debian 12's to this mono version to match? 

user@20230802$ mono --version
Mono JIT compiler version 6.12.0.200 (tarball Tue Jul 11 21:33:00 UTC 2023)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

**Comment by Kenny-Hui** [comment]
Hmm I can reproduce this under Wine as well, now that's interesting...
I don't think there's any specific correlation or configuration that could affect this...

**Comment by leezer3** [comment]
I'd agree with the route related, but only in the sense it'll be hanging up the timing somewhere.
Larger routes will be by definition slower to load & more prone.

10k signal sections is somewhat excessive, and I'm not surprised it causes slowdowns.

**Comment by Kenny-Hui** [comment]
Nope it seems to happen regardless of route.
After tinkering around, the only conclusion I can come up with is that I cancelled the route loading (switch route) before the all the content plugin could be fully loaded.

The same crash should also happen on Windows if you add something like a Thread.Sleep(2000) on LoadPlugins().
Why can I never get it to crash under normal circumstances is beyond me, maybe it's timing related.

**Comment by ginga81** [comment]
I think we should download and verify this TFO sample route to switch the exact same data to each other to reproduce the bug.
Actually, there is no problem in my environment and leeser3's,  only one person does not move, is it?
https://bveworldwide.forumotion.com/t2301-animating-an-overtaking-train#21357

**Comment by Kenny-Hui** [comment]
Ok I've downloaded the TFO sample route and reproduced it under Wine 8.0.2

https://github.com/leezer3/OpenBVE/assets/28094366/c3504bd6-9c93-43e9-bf58-36d245de3e50

(Still the same crash log)

**Comment by ginga81** [comment]
The video was very helpful!
When I switched the TFO sample route at the same speed, I got the same error as you, so I was able to reproduce it.
You have to press it pretty quickly.
I pushed it slowly.

**Comment by Kenny-Hui** [comment]
Reproducible under Windows, just have to be really quick about it.

(Both hand, Mouse Click + Arrow Down immediately should be easier to reproduce)

**Comment by leezer3** [comment]
Still not at the minute :(

Will try a slower machine at some point, but that trigger is almost enough to ignore:/
