### ISSUE TITLE
 Densha De Go Controller Plugin Not Registering Controller

### ISSUE THREAD

**Issue by seabirdgh** [leezer3/OpenBVE#995]
### Description

I have been having trouble trying to set up the Zuiki One Handled Controller using the inbuilt controller plugin in OpenBve. When I plug the controller in and click the config button it will show this: 
![Screenshot 2024-02-22 184545](https://github.com/leezer3/OpenBVE/assets/160849015/031d41a8-f134-4527-89fa-d7f1de94fe53)
and then close. The controller I am using is "ZUIKI MasCon for Nintendo Switch BLUE" which is a one handle controller.
![l7WkM4iEWaKPBevBYg4A5w==](https://github.com/leezer3/OpenBVE/assets/160849015/7c8bf7eb-e45e-4e4d-8793-334464a83d14)

### Reproduction

Connect  ZUIKI MasCon for Nintendo Switch BLUE/RED to your computer and enable the controller plugin then click config

## Route

n/a

## Train

n/a

## Logs

Logs may be accessed through the 'Report Problem' button on the bottom left of the screen.
Please provide a log, and a crash-log if the game actually crashes.
[log.txt](https://github.com/leezer3/OpenBVE/files/14372777/log.txt)
[OpenBVE Crash- 2024.2.22[18.45].log](https://github.com/leezer3/OpenBVE/files/14372778/OpenBVE.Crash-.2024.2.22.18.45.log)

### Related information 

* Operating system : windows 10
* Method of control (ZUIKI MasCon for Nintendo Switch)
* Version : OpenBVE v1.9.2.7

**Comment by leezer3** [comment]
@MarcRiera
I think we've got a PID for the DenshaDeGo! Zuki we haven't seen before.

I've fixed the immediate crashing error, and it'll now add the PID to the logfile as you intended, but further than that we obviously need the PID. 
I wonder whether it's worth mapping all PIDs for Zuki / Hori by default??

@seabirdgh 
Please could you give us another log with the new build from today?
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2024-02-22.zip

This should hopefully now not crash, and add the PID we need to fix this. Many thanks :)

**Comment by leezer3** [comment]
Incidentally, thinking about this I'd suspect there probably to be 2 new VIDs.

**Reasoning:**
I've just remembered that the Switch supports showing the color of the current joycon shell in it's UI.
This is done via the Bluetooth SPI device descriptor, but I suspect it'll probably do exactly the same for Zuki USB peripherals. 
Assuming this is the case, and our offending new device is on the next incremental PID 3 (or 4), I'd probably add the other on spec no matter what you think.

**Comment by seabirdgh** [comment]
Log from today's build. Open bve still crashes still crashes.
[log.txt](https://github.com/leezer3/OpenBVE/files/14373247/log.txt)
[OpenBVE Crash- 2024.2.22[19.34].log](https://github.com/leezer3/OpenBVE/files/14373248/OpenBVE.Crash-.2024.2.22.19.34.log)

**Comment by leezer3** [comment]
OK, that exposed a second different issue with trying to add a game message to the queue if it hadn't fully spun up :(

Game and the log ought to work this time...
(Build will automatically regenerate in a few minutes)

**Comment by seabirdgh** [comment]
Thanks!
